### ISSUE TITLE
Why training generator with defense mechanism requries Normalize and Permute?

### ISSUE THREAD

**Issue by machanic** [TransEmbedBA/TREMBA#3]
https://github.com/TransEmbedBA/TREMBA/blob/master/train_generator.py#L45
https://github.com/TransEmbedBA/TREMBA/blob/master/train_generator.py#L51
Why `if 'defense' in state and state['defense']:` needs the `Normalize` and `Permute`?

**Comment by HuangZhiChao95** [comment]
The is the setting in the original model. I just use their weights.
