### ISSUE TITLE
A question about l-inf attack for AutoZOOM 

### ISSUE THREAD

**Issue by lin2020** [TransEmbedBA/TREMBA#4]
Hi, I found that in your paper, you have performed l-inf attack with AutoZOOM. 
However, I found that the source code of AutoZOOM only perform the l-2 attack, 
how can I modify the source code of AutoZOOM to perform the l-inf attack?
I would appreciate it if you could help me.

**Comment by HuangZhiChao95** [comment]
Just as TREMBA, we add tanh after the generator to limit the l-inf norm. We do not add l2 term in the loss, and the loss for AutoZOOM is just the hinge loss. Other things are the same as the original paper.

**Comment by lin2020** [comment]
Thanks.
