### ISSUE TITLE
Does generator_name in attack_untarget.json have a relationship with model in attack.py?

### ISSUE THREAD

**Issue by Kitzzaaa** [TransEmbedBA/TREMBA#7]

**Comment by HuangZhiChao95** [comment]
Yes. If the args.model_name is not specified in the command line, it will use the model_name provided in the corresponding json file.

**Comment by Kitzzaaa** [comment]
@HuangZhiChao95 
1.I mean if args.model_name is resnet50, vgg16_bn, inception_v3 or others  can all use generator_name in attack_untarget.json?
2.And if args.model_name is inception_v3, how should I set the following 120 lines in FCN.py?

![屏幕截图 2022-03-07 093603](https://user-images.githubusercontent.com/75681041/156953261-d249ac34-aa14-447d-87f0-cc205a2b01f6.png)

**Comment by HuangZhiChao95** [comment]
The model_name only support ResNet34, VGG19, DenseNet121 and Mobilenet as shown in line111-line117 in attack.py. You can add new code here to provide support for new architectures.

As Inception_V3 use different input dimension (299x299), the code is not applicable to it.
